FROM ekapusta/alpine-sshd

WORKDIR /etc/ssh

RUN \
  apk --no-cache add git perl && \
  # Add group named "git"
  addgroup git && \
  # Add user without password to group "git" with name "git"
  adduser -D -G git -s /bin/sh git && \
  # Unlock git account (as it was with empty password)
  passwd -u git && \
  # Forbid SSH password auth for git user
  ( \
    echo ""; \
    echo "# Gitolite changes from $(date)"; \
    echo "Match User git"; \
    echo "    PasswordAuthentication no"; \
  ) >> sshd_config

USER git
WORKDIR /home/git

ENV PATH /home/git/gitolite/src:$PATH

RUN \
  git clone git://github.com/sitaramc/gitolite && \
  test -f .ssh/id_rsa.pub || ( \
    mkdir .ssh && \
    ssh-keygen -t rsa -b 2048 -f .ssh/id_rsa -N '' && \
    echo "Autogenerated public key:" && \
    cat .ssh/id_rsa.pub && \
    echo \
  ) && \
  touch .ssh/authorized_keys && \
  USER=$(whoami) gitolite setup --pubkey ~/.ssh/id_rsa.pub

USER root
