FROM ekapusta/alpine-sshd

RUN \
  apk --no-cache add git perl && \
  # Add group named "git"
  addgroup git && \
  # Add user without password to group "git" with name "git"
  adduser -D -G git -s /bin/sh git && \
  # Unlock git account (as it was with empty password)
  passwd -u git && \
  # Forbid SSH password auth for git user
  ( \
    echo ""; \
    echo "# Gitolite changes from $(date)"; \
    echo "Match User git"; \
    echo "    PasswordAuthentication no"; \
  ) >> /etc/ssh/sshd_config && \
  VOL-save /etc/ssh

USER git
WORKDIR /home/git

ENV PATH /home/git/gitolite/src:$PATH
ENV GITOLITE_REMOTE git://github.com/sitaramc/gitolite

RUN \
  GITOLITE_STABLE=$(\
    git ls-remote --tags $GITOLITE_REMOTE | \
    grep -o 'v3.*[0-9]$' | \
    sort -t '.' -k 2,3 -g | \
    tail -1 \
  ) && \
  git clone --depth 1 --branch $GITOLITE_STABLE $GITOLITE_REMOTE && \
  test -f .ssh/id_rsa.pub || ( \
    mkdir .ssh && \
    ssh-keygen -t rsa -b 2048 -f .ssh/id_rsa -N '' && \
    echo "Autogenerated public key:" && \
    cat .ssh/id_rsa.pub && \
    echo \
  ) && \
  touch .ssh/authorized_keys

USER root

RUN \
  echo "su git -c 'USER=git gitolite setup --pubkey ~/.ssh/id_rsa.pub'" > /dcr/cm.d/090-gitolite-050-setup
